# Generated by Django 5.2.4 on 2025-07-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование товара')),
                ('image', models.ImageField(blank=True, upload_to='products_images/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('shoort_description', models.CharField(blank=True, max_length=64, verbose_name='Краткое описание товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='Категория товара')),
            ],
        ),
    ]
