# Generated by Django 5.2.4 on 2025-07-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shoort_description',
            new_name='short_description',
        ),
    ]
